feature/header: Add header with breadcrumbs, dropdown, logo
xabierlameiro/clean-started pull request #5
Opened 2023-05-19 10:51 UTC by gabyballester

2023-05-19 11:02 UTC, xabierlameiro commented on public/logo1.png
Por qué el cambio de nombre?

2023-05-19 11:06 UTC, xabierlameiro commented on src/components/header/components/dropdown/data/index.ts
LLevemos las constantes /src/constants como has hecho con icons

2023-05-19 12:42 UTC, gabyballester commented on public/logo1.png
Cambiado a logo.png de nuevo, ya que se está usando en más sitios.
Si más adelante se necesita otro para el header, ya lo cambiamos.

2023-05-19 13:01 UTC, gabyballester commented on src/components/header/components/dropdown/data/index.ts
Done.

2023-05-19 13:52 UTC, gabyballester commented
- Agregada carpeta mocks
- Agregado path @/mocks
- Cambiado logo1.png a logo.png
- Renombrado de componentes a index.tsx dejando sus carpetas con Mayúsculas

2023-05-22 06:45 UTC, xabierlameiro commented on src/components/Header/components/Dropdown/index.tsx
> +import { icons } from 'src/constants/icons';
@/constants

2023-05-22 06:47 UTC, xabierlameiro requested changes

2023-05-22 06:47 UTC, xabierlameiro commented on src/components/Header/components/Crumb/index.tsx
> +import { capitalize } from 'src/helpers/capitalize';
creemos en tsconfig la ruta para @/helpers y usemosla

2023-05-22 08:52 UTC, gabyballester commented on src/components/Header/components/Dropdown/index.tsx
> +import { icons } from 'src/constants/icons';
Done

2023-05-22 08:53 UTC, gabyballester commented on src/components/Header/components/Crumb/index.tsx
> +import { capitalize } from 'src/helpers/capitalize';
Done

2023-05-22 09:04 UTC, xabierlameiro commented on src/components/Header/components/Crumb/index.tsx
> +import { capitalize } from 'src/helpers/capitalize';
Revisa, pero creo que no has hecho push

2023-05-22 09:06 UTC, xabierlameiro approved these changes

2023-05-22 09:06 UTC, merged

2023-05-22 09:08 UTC, gabyballester commented on src/components/Header/components/Crumb/index.tsx
> +import { capitalize } from 'src/helpers/capitalize';
Normalmente pongo los comentarios y luego hago el commit y el push, prefieres que lo hagamos de otro modo? Realmente no hemos definido como hacerlo.